[build]
builder = "DOCKERFILE"
dockerfilePath = "services/order/Dockerfile"

[deploy]
healthcheckPath = "/health/live"
healthcheckTimeout = 120
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5
